In [6]:
import numpy as np

In [7]:
np

<module 'numpy' from '/opt/anaconda3/lib/python3.8/site-packages/numpy/__init__.py'>

In [5]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
!ls /opt/anaconda3/lib/python3.8/site-packages/numpy/

LICENSE.txt            conftest.py            ma
__config__.py          core                   matlib.py
__init__.cython-30.pxd ctypeslib.py           matrixlib
__init__.pxd           ctypeslib.pyi          polynomial
__init__.py            distutils              py.typed
__init__.pyi           doc                    random
__pycache__            dual.py                rec.pyi
_distributor_init.py   emath.pyi              setup.py
_globals.py            f2py                   testing
_pytesttester.py       fft                    tests
char.pyi               lib                    typing
compat                 linalg                 version.py


In [8]:
ar1=np.array([1,2,3])

In [9]:
ar1

array([1, 2, 3])

In [10]:
type(ar1)

numpy.ndarray

In [11]:
ar1.ndim

1

In [12]:
ar1.shape

(3,)

In [13]:
ar1*2

array([2, 4, 6])

In [14]:
ar1**2

array([1, 4, 9])

In [15]:
ar2=np.array([5,6,7,8.0])

In [16]:
ar2

array([5., 6., 7., 8.])

# Creating arrays within a range using Numpy

In [17]:
m1=np.arange(1,10)

In [18]:
m1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
type(m1)

numpy.ndarray

In [20]:
np.arange(1,10,0.5)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. ,
       7.5, 8. , 8.5, 9. , 9.5])

In [21]:
# set dtype as float

In [22]:
np.arange(1,10,dtype="float").reshape(3,3)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [23]:
# how numpy arrays behave like C

In [24]:
100**10

100000000000000000000

In [25]:
np.array([1,2,3,100])**10          #overflow

array([                  1,                1024,               59049,
       7766279631452241920])

In [26]:
np.array([1,2,3.5])   # it converts all te elements into float

array([1. , 2. , 3.5])

<!-- Matrices and N-dimensional array -->


 Matirces and N-dimensional array

In [28]:
m1=np.arange(1,25).reshape(4,6)

In [31]:
m1   #2-D arraay using range

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [32]:
m1.reshape(6,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [33]:
m1

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [38]:
m1.reshape(24,1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [39]:
m1.reshape(1,24)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22, 23, 24]])

In [40]:
m1.ndim

2

In [41]:
type(m1)

numpy.ndarray

In [42]:
m1.shape

(4, 6)

In [48]:
m2=np.arange(1,10).reshape(9,)

In [49]:
m2

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
m3=np.arange(1,10).reshape(9,1)

In [51]:
m3

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [52]:
m2.shape

(9,)

In [53]:
m3.shape

(9, 1)

In [54]:
m2.ndim

1

In [55]:
m3.ndim

2

In [56]:
type(m2)

numpy.ndarray

In [57]:
type(m3)

numpy.ndarray

Special Arrays in Numpy

In [59]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [60]:
np.zeros(9).reshape(3,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [61]:
np.zeros(12).reshape(4,3)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [62]:
np.zeros(12).reshape(6,2)

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [63]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [64]:
np.ones(12).reshape(4,3)

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [65]:
np.ones(12).reshape(6,2)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [66]:
# Additin and multilication in zeros and ones arrray

In [67]:
z=np.zeros(12).reshape(4,3)

In [70]:
z+2

array([[2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.],
       [2., 2., 2.]])

In [71]:
z*2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [74]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [77]:
np.ones((4,6))*2

array([[2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2.]])

In [78]:
np.ones((4,6))*9

array([[9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9.],
       [9., 9., 9., 9., 9., 9.]])

In [79]:
np.ones((4,6))+3

array([[4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4.],
       [4., 4., 4., 4., 4., 4.]])

In [81]:
# Diagonal Matrix in numpy
np.diag([1,2,3])

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [83]:
np.diag([12,23,45])*1.5

array([[18. ,  0. ,  0. ],
       [ 0. , 34.5,  0. ],
       [ 0. ,  0. , 67.5]])

In [84]:
# Identity matrix 

In [85]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [87]:
np.identity(9)*2

array([[2., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 2., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 2., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 2., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 2., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 2., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 2., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 2., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 2.]])

In [89]:
i=np.identity(9)+3

In [90]:
i

array([[4., 3., 3., 3., 3., 3., 3., 3., 3.],
       [3., 4., 3., 3., 3., 3., 3., 3., 3.],
       [3., 3., 4., 3., 3., 3., 3., 3., 3.],
       [3., 3., 3., 4., 3., 3., 3., 3., 3.],
       [3., 3., 3., 3., 4., 3., 3., 3., 3.],
       [3., 3., 3., 3., 3., 4., 3., 3., 3.],
       [3., 3., 3., 3., 3., 3., 4., 3., 3.],
       [3., 3., 3., 3., 3., 3., 3., 4., 3.],
       [3., 3., 3., 3., 3., 3., 3., 3., 4.]])

In [91]:
type(i)

numpy.ndarray

In [93]:
np.ndim(i)

2

In [94]:
i.shape

(9, 9)

Operation that can be performed in ndarray

In [105]:
# indexing
nd=np.arange(1,17).reshape(4,4)

In [106]:
nd

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [107]:
nd[0]

array([1, 2, 3, 4])

In [108]:
nd[0][1]

2

In [109]:
nd[0,1]

2

In [110]:
nd[0,2:]

array([3, 4])

In [111]:
nd[2:]

array([[ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [112]:
nd[:3,1:3]

array([[ 2,  3],
       [ 6,  7],
       [10, 11]])

In [114]:
nd[:,(1,3)]

array([[ 2,  4],
       [ 6,  8],
       [10, 12],
       [14, 16]])

In [116]:
nd[:,(0,2,3)]

array([[ 1,  3,  4],
       [ 5,  7,  8],
       [ 9, 11, 12],
       [13, 15, 16]])

#  Algebric operations on np arrays with single numbers